"""
Django settings for msict_ordering project.

Generated by 'django-admin startproject' using Django 5.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""


import os
import dj_database_url
from pathlib import Path
#import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-qb@7-&-nj$unp9a2@p$jd_^sgp8l3sf^90d=&g-gv7+)95lm-('

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'orders',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
]

ROOT_URLCONF = 'msict_ordering.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'msict_ordering.wsgi.application'


#Database
#https://docs.djangoproject.com/en/5.0/ref/settings/#databases


# Database configuration
# if 'DATABASE_URL' in os.environ:
#     Production database (PostgreSQL on Render)
DATABASES = {
    'default': dj_database_url.config(
        default='postgresql://msict_k8tg_user:NUkleyrP5Bc3Wp53BPKtkJvBAU262bKQ@dpg-d19s2p6mcj7s73erg4hg-a.oregon-postgres.render.com/msict_k8tg',
        conn_max_age=600,
        conn_health_checks=True,
    )
}

# else:
    # Development database (SQLite)
# DATABASES = {
#         'default': {
#             'ENGINE': 'django.db.backends.sqlite3',
#             'NAME': BASE_DIR / 'db.sqlite3',
#             'OPTIONS': {
#                 'timeout': 30, 
#             }
#         }
#     }


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Dar_es_Salaam'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Jazzmin Admin Settings
JAZZMIN_SETTINGS = {
    "site_title": "MSICT Ordering Admin",
    "site_header": "MSICT Ordering",
    "site_brand": "MSICT Offices",
    "site_logo": "orders/img/msict_logo.png",
    "site_logo_classes": "img-circle",
    "site_icon": "orders/img/msict_favicon.ico",
    "welcome_sign": "Welcome to MSICT Offices Ordering System",
    "copyright": "Military School of ICT",
    "search_model": ["auth.User", "auth.Group", "orders.Order", "orders.Equipment"],
    "topmenu_links": [
        {"name": "Home", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "Support", "url": "https://msict.mil.tz/support", "new_window": True},
        {"model": "auth.User"},
        {"app": "orders"},
    ],
    "usermenu_links": [
        {"name": "MSICT Portal", "url": "https://msict.mil.tz", "new_window": True},
        {"model": "auth.user"}
    ],
    "show_sidebar": True,
    "navigation_expanded": True,
    "order_with_respect_to": [
        "auth", 
        "orders", 
        "orders.Department", 
        "orders.Equipment", 
        "orders.Order"
    ],
    "custom_links": {
        "orders": [
            {
                "name": "Quick Order", 
                "url": "make_order", 
                "icon": "fas fa-plus-circle",
                "permissions": ["orders.add_order"]
            },
            {
                "name": "Inventory Report", 
                "url": "inventory_report", 
                "icon": "fas fa-clipboard-list",
                "permissions": ["orders.view_equipment"]
            }
        ]
    },
    "icons": {
        "auth": "fas fa-users-shield",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "orders.Department": "fas fa-building",
        "orders.Equipment": "fas fa-laptop",
        "orders.Order": "fas fa-clipboard-check",
        "orders.OrderItem": "fas fa-boxes",
    },
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
    "related_modal_active": True,
    "custom_css": "orders/css/admin_custom.css",
    "use_google_fonts_cdn": True,
    "show_ui_builder": False,
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {
        "auth.user": "collapsible", 
        "auth.group": "vertical_tabs",
        "orders.Order": "vertical_tabs",
    },
    "language_chooser": False,
}

# Email Settings (example configuration)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.mail.mil.tz'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'noreply@msict.mil.tz'
EMAIL_HOST_PASSWORD = 'your-email-password'
DEFAULT_FROM_EMAIL = 'MSICT Ordering System <noreply@msict.mil.tz>'

# Authentication Settings
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/admin/'
LOGOUT_REDIRECT_URL = '/login/'

# Security settings (for production)
if not DEBUG:
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'