# Generated by Django 5.1.5 on 2025-06-18 08:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="departmentrequest",
            name="estimated_cost",
        ),
        migrations.RemoveField(
            model_name="departmentrequest",
            name="priority",
        ),
    ]
